-- Migration: Backfill puzzle_stats from game_results
-- Run this ONCE after creating the puzzle_stats table
-- This re-aggregates all historical data by puzzle_num instead of play_date

-- Step 1: Create the table (safe to run multiple times)
CREATE TABLE IF NOT EXISTS puzzle_stats (
  puzzle_num INTEGER NOT NULL,
  country TEXT DEFAULT 'ALL',
  total_players INTEGER DEFAULT 0,
  total_wins INTEGER DEFAULT 0,
  total_guesses INTEGER DEFAULT 0,
  total_time INTEGER DEFAULT 0,
  dist_1 INTEGER DEFAULT 0,
  dist_2 INTEGER DEFAULT 0,
  dist_3 INTEGER DEFAULT 0,
  dist_4 INTEGER DEFAULT 0,
  dist_5 INTEGER DEFAULT 0,
  dist_6 INTEGER DEFAULT 0,
  b1_played INTEGER DEFAULT 0,
  b1_won INTEGER DEFAULT 0,
  b2_played INTEGER DEFAULT 0,
  b2_won INTEGER DEFAULT 0,
  shared_count INTEGER DEFAULT 0,
  mobile_count INTEGER DEFAULT 0,
  desktop_count INTEGER DEFAULT 0,
  keyboard_count INTEGER DEFAULT 0,
  numpad_count INTEGER DEFAULT 0,
  bc_used_count INTEGER DEFAULT 0,
  first_guess_sum INTEGER DEFAULT 0,
  dark_count INTEGER DEFAULT 0,
  scheme_0 INTEGER DEFAULT 0,
  scheme_1 INTEGER DEFAULT 0,
  scheme_2 INTEGER DEFAULT 0,
  scheme_3 INTEGER DEFAULT 0,
  streak_sum INTEGER DEFAULT 0,
  streak_max INTEGER DEFAULT 0,
  both_count INTEGER DEFAULT 0,
  bc_win_count INTEGER DEFAULT 0,
  shared_win_count INTEGER DEFAULT 0,
  shared_loss_count INTEGER DEFAULT 0,
  b1_first_try INTEGER DEFAULT 0,
  both_won INTEGER DEFAULT 0,
  updated_at TEXT DEFAULT (datetime('now')),
  PRIMARY KEY (puzzle_num, country)
);

CREATE INDEX IF NOT EXISTS idx_puzzle_stats_num ON puzzle_stats(puzzle_num);

-- Step 2: Backfill per-country stats from game_results
INSERT OR REPLACE INTO puzzle_stats (
  puzzle_num, country,
  total_players, total_wins, total_guesses, total_time,
  dist_1, dist_2, dist_3, dist_4, dist_5, dist_6,
  b1_played, b1_won, b2_played, b2_won, shared_count,
  mobile_count, desktop_count, keyboard_count, numpad_count,
  bc_used_count, first_guess_sum,
  dark_count, scheme_0, scheme_1, scheme_2, scheme_3,
  streak_sum, streak_max, both_count, bc_win_count,
  shared_win_count, shared_loss_count,
  b1_first_try, both_won
)
SELECT
  puzzle_num,
  country,
  COUNT(*) as total_players,
  SUM(won) as total_wins,
  SUM(guesses) as total_guesses,
  SUM(total_time) as total_time,
  SUM(CASE WHEN won=1 AND guesses=1 THEN 1 ELSE 0 END) as dist_1,
  SUM(CASE WHEN won=1 AND guesses=2 THEN 1 ELSE 0 END) as dist_2,
  SUM(CASE WHEN won=1 AND guesses=3 THEN 1 ELSE 0 END) as dist_3,
  SUM(CASE WHEN won=1 AND guesses=4 THEN 1 ELSE 0 END) as dist_4,
  SUM(CASE WHEN won=1 AND guesses=5 THEN 1 ELSE 0 END) as dist_5,
  SUM(CASE WHEN won=1 AND guesses=6 THEN 1 ELSE 0 END) as dist_6,
  SUM(CASE WHEN b1_result != 'none' THEN 1 ELSE 0 END) as b1_played,
  SUM(CASE WHEN b1_result LIKE 'win%' THEN 1 ELSE 0 END) as b1_won,
  SUM(CASE WHEN b2_result != 'none' THEN 1 ELSE 0 END) as b2_played,
  SUM(CASE WHEN b2_result LIKE 'win%' THEN 1 ELSE 0 END) as b2_won,
  SUM(shared) as shared_count,
  SUM(mobile) as mobile_count,
  SUM(CASE WHEN mobile=0 THEN 1 ELSE 0 END) as desktop_count,
  SUM(CASE WHEN input_method='keyboard' OR input_method='both' THEN 1 ELSE 0 END) as keyboard_count,
  SUM(CASE WHEN input_method='numpad' OR input_method='both' THEN 1 ELSE 0 END) as numpad_count,
  SUM(used_bc) as bc_used_count,
  SUM(first_guess) as first_guess_sum,
  SUM(dark_mode) as dark_count,
  SUM(CASE WHEN color_scheme=0 THEN 1 ELSE 0 END) as scheme_0,
  SUM(CASE WHEN color_scheme=1 THEN 1 ELSE 0 END) as scheme_1,
  SUM(CASE WHEN color_scheme=2 THEN 1 ELSE 0 END) as scheme_2,
  SUM(CASE WHEN color_scheme=3 THEN 1 ELSE 0 END) as scheme_3,
  SUM(streak) as streak_sum,
  MAX(streak) as streak_max,
  SUM(CASE WHEN input_method='both' THEN 1 ELSE 0 END) as both_count,
  SUM(CASE WHEN used_bc=1 AND won=1 THEN 1 ELSE 0 END) as bc_win_count,
  SUM(CASE WHEN shared=1 AND won=1 THEN 1 ELSE 0 END) as shared_win_count,
  SUM(CASE WHEN shared=1 AND won=0 THEN 1 ELSE 0 END) as shared_loss_count,
  SUM(CASE WHEN b1_result='win-1' THEN 1 ELSE 0 END) as b1_first_try,
  SUM(CASE WHEN b1_result LIKE 'win%' AND b2_result LIKE 'win%' THEN 1 ELSE 0 END) as both_won
FROM game_results
GROUP BY puzzle_num, country;

-- Step 3: Backfill 'ALL' country aggregate
INSERT OR REPLACE INTO puzzle_stats (
  puzzle_num, country,
  total_players, total_wins, total_guesses, total_time,
  dist_1, dist_2, dist_3, dist_4, dist_5, dist_6,
  b1_played, b1_won, b2_played, b2_won, shared_count,
  mobile_count, desktop_count, keyboard_count, numpad_count,
  bc_used_count, first_guess_sum,
  dark_count, scheme_0, scheme_1, scheme_2, scheme_3,
  streak_sum, streak_max, both_count, bc_win_count,
  shared_win_count, shared_loss_count,
  b1_first_try, both_won
)
SELECT
  puzzle_num,
  'ALL',
  COUNT(*) as total_players,
  SUM(won) as total_wins,
  SUM(guesses) as total_guesses,
  SUM(total_time) as total_time,
  SUM(CASE WHEN won=1 AND guesses=1 THEN 1 ELSE 0 END) as dist_1,
  SUM(CASE WHEN won=1 AND guesses=2 THEN 1 ELSE 0 END) as dist_2,
  SUM(CASE WHEN won=1 AND guesses=3 THEN 1 ELSE 0 END) as dist_3,
  SUM(CASE WHEN won=1 AND guesses=4 THEN 1 ELSE 0 END) as dist_4,
  SUM(CASE WHEN won=1 AND guesses=5 THEN 1 ELSE 0 END) as dist_5,
  SUM(CASE WHEN won=1 AND guesses=6 THEN 1 ELSE 0 END) as dist_6,
  SUM(CASE WHEN b1_result != 'none' THEN 1 ELSE 0 END) as b1_played,
  SUM(CASE WHEN b1_result LIKE 'win%' THEN 1 ELSE 0 END) as b1_won,
  SUM(CASE WHEN b2_result != 'none' THEN 1 ELSE 0 END) as b2_played,
  SUM(CASE WHEN b2_result LIKE 'win%' THEN 1 ELSE 0 END) as b2_won,
  SUM(shared) as shared_count,
  SUM(mobile) as mobile_count,
  SUM(CASE WHEN mobile=0 THEN 1 ELSE 0 END) as desktop_count,
  SUM(CASE WHEN input_method='keyboard' OR input_method='both' THEN 1 ELSE 0 END) as keyboard_count,
  SUM(CASE WHEN input_method='numpad' OR input_method='both' THEN 1 ELSE 0 END) as numpad_count,
  SUM(used_bc) as bc_used_count,
  SUM(first_guess) as first_guess_sum,
  SUM(dark_mode) as dark_count,
  SUM(CASE WHEN color_scheme=0 THEN 1 ELSE 0 END) as scheme_0,
  SUM(CASE WHEN color_scheme=1 THEN 1 ELSE 0 END) as scheme_1,
  SUM(CASE WHEN color_scheme=2 THEN 1 ELSE 0 END) as scheme_2,
  SUM(CASE WHEN color_scheme=3 THEN 1 ELSE 0 END) as scheme_3,
  SUM(streak) as streak_sum,
  MAX(streak) as streak_max,
  SUM(CASE WHEN input_method='both' THEN 1 ELSE 0 END) as both_count,
  SUM(CASE WHEN used_bc=1 AND won=1 THEN 1 ELSE 0 END) as bc_win_count,
  SUM(CASE WHEN shared=1 AND won=1 THEN 1 ELSE 0 END) as shared_win_count,
  SUM(CASE WHEN shared=1 AND won=0 THEN 1 ELSE 0 END) as shared_loss_count,
  SUM(CASE WHEN b1_result='win-1' THEN 1 ELSE 0 END) as b1_first_try,
  SUM(CASE WHEN b1_result LIKE 'win%' AND b2_result LIKE 'win%' THEN 1 ELSE 0 END) as both_won
FROM game_results
GROUP BY puzzle_num;
